return {
	Rarity = {
		Common = "Common",
		Uncommon = "Uncommon",
		Rare = "Rare",
		Epic = "Epic",
		Legendary = "Legendary",
	},

	CarryState = {
		EmptyHands = "EmptyHands",
		CarryingPrepared = "CarryingPrepared",
		CarryingBaked = "CarryingBaked",
	},

	TableState = {
		Idle = "Idle",
		AwaitingIngredients = "AwaitingIngredients",
		Preparing = "Preparing",
		ReadyToCollect = "ReadyToCollect",
	},

	OvenState = {
		Idle = "Idle",
		Baking = "Baking",
		ReadyToCollect = "ReadyToCollect",
	},
}
